version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yml
      - ./loki/data:/loki

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
#      - /logs:/mogak/logs
      - /Users/kongmac/Desktop/mogak/logs:/mogak/logs
      - ./promtail/promtail-config.yml:/etc/promtail/promtail.yml
      - ./promtail/positions:/tmp
    command: -config.file=/etc/promtail/promtail.yml